### ISSUE TITLE
Режим часов не работает на esp8266

### ISSUE THREAD

**Issue by degorychev** [AlexGyver/SegmentMonitor#1]
Спаял плату, все режимы запускаются и работают четко, кроме самого основного - часов. 
esp в серийный монитор спамит ошибкой:

>  ets Jan  8 2013,rst cause:2, boot mode:(3,6)
> load 0x4010f000, len 3424, room 16 
> tail 0
> chksum 0x2e
> load 0x3fff20b8, len 40, room 8 
> tail 0
> chksum 0x2b
> csum 0x2b
> v00042330
> ~ld

Если прошивку скомпилировать на arduino - то все хорошо, подозреваю что существует какая то разница в работе с PROGMEM памятью между arduino и esp. небольшое гугление привело вот к этой [Ссылке](https://github.com/esp8266/Arduino/issues/5361). Но как использовать эту информацию - не понимаю, прошу помощи...

**Comment by GyverLibs** [comment]
Да, 4 байт align имеет место быть, но в этом коде он не должен влиять. Завтра найду макет, протестирую. Спасибо

**Comment by degorychev** [comment]
> Завтра найду макет, протестирую.

Хоть какие нибудь успехи?

**Comment by GyverLibs** [comment]
Не было времени :( работать будет 100%, за это можно не беспокоиться)

**Comment by AlexGyver** [comment]
Вот это я тупанул, у есп же 32 бит адресация. Одной буквы в коде не хватало 🤣🤣🤣
![image](https://user-images.githubusercontent.com/21090953/215359795-3e816f82-8ee5-40a6-af96-7120a13066a8.png)

**Comment by degorychev** [comment]
> Одной буквы в коде не хватало

Благодарю! А я вот наоборот пытался при помощи pgm_read_byte сделать, читая [Страничку](https://alexgyver.ru/lessons/progmem/) уроков, так как вроде для uint8_t она используется. Может стоить сделать какую то сноску что в случает esp оно работает иначе там?

**Comment by GyverLibs** [comment]
Я добавил данную ситуацию в урок. Тут хитрость в том, что мы читаем адрес массива в "списке" (массив адрес первого члена), то есть в массиве адресов массивов. А адресация у есп 32 битная, поэтому если читать байт или ворд - либо повезёт, если адрес меньше 65535 (инт), или не повезет и программа будет читать данные оттуда откуда нельзя, что у нас и получилось)
